### ISSUE TITLE
Workflow vs Web Search

### ISSUE THREAD

**Issue by Acidham** [svsool/alfred-explainshell#1]
What is the additional value of having a Workflow implementation instead of a Alfred Web Search entry?

Or is it planned to add available commands and options in script filter?

**Comment by svsool** [comment]
Hi @Acidham, there is no additional value at the moment. My initial idea was to provide information about inputted command in the search results in a similar way how other workflows do that, but I haven't found any available API for https://explainshell.com/ and just ended up to use the shortcut that redirects to it directly.
